---
# Install and configure PostgreSQL

- name: Install PostgreSQL
  yum: name={{ item }} state=latest
  with_items:
    - python-psycopg2
    - postgresql96-server
    - postgresql96
  tags: postgresql

- name: Initialize the PostgreSQL database
  command: /usr/pgsql-9.6/bin/postgresql96-setup initdb creates=/var/lib/pgsql/9.6/data/postgresql.conf
  tags: postgresql

- name: Start the PostgreSQL server
  service: name=postgresql-9.6 enabled=yes state=started
  tags: postgresql

# If there's only one web server and it's the same as the DB server, then only
# listen on localhost
- name: Configure PostgreSQL to listen on localhost
  lineinfile: dest=/var/lib/pgsql/9.6/data/postgresql.conf regexp='^#?listen_addresses\s*=' line="listen_addresses = '127.0.0.1'" state=present
  notify: restart postgresql
  when: groups['webservers']|count == 1 and groups['webservers'][0] == groups['dbserver'][0]
  tags: postgresql

# If there's more than one web server, or if the web and db servers aren't
# the same host, then open up to external hosts, including via iptables
- name: Configure PostgreSQL to listen for external hosts
  lineinfile: dest=/var/lib/pgsql/9.6/data/postgresql.conf regexp='^#?listen_addresses\s*=' line="listen_addresses = '*'" state=present
  notify: restart postgresql
  when: groups['webservers']|count > 1 or groups['webservers'][0] != groups['dbserver'][0]
  tags: postgresql

- name: Open iptables firewall for PostgreSQL
  command: /sbin/iptables -A INPUT -p tcp --dport 5432 -j ACCEPT
  when: groups['webservers']|count > 1 or groups['webservers'][0] != groups['dbserver'][0]
  tags: postgresql

- name: Save iptables configuration
  command: /sbin/service iptables save
  when: groups['webservers']|count > 1 or groups['webservers'][0] != groups['dbserver'][0]
  tags: postgresql

- name: Create the RLetters PostgreSQL database
  become: yes
  become_user: postgres
  postgresql_db: db=rletters_production
  tags: postgresql

- name: Create a user with access to the PostgreSQL database
  become: yes
  become_user: postgres
  postgresql_user: db=rletters_production user=rletters_postgresql priv=ALL password={{ db_pass }}
  tags: postgresql

- name: Tighten privileges on PostgreSQL user
  become: yes
  become_user: postgres
  postgresql_user: db=rletters_production user=rletters_postgresql role_attr_flags=NOSUPERUSER,NOCREATEDB
  tags: postgresql

- name: Enable MD5 authentication for PostgreSQL over TCP even from localhost
  lineinfile: dest=/var/lib/pgsql/9.6/data/pg_hba.conf regexp='host\s+all\s+all\s+127.0.0.1/32\s+md5' line='host all all 127.0.0.1/32 md5' insertbefore=BOF
  notify: restart postgresql
  tags: postgresql
